web/crux/.eslintrc.js
Problem: The error `Parsing error: Cannot read file '.../tsconfig.json'.eslint` shows in all .ts files in the src folder including index.ts.
By default, the projects (in parserOptions) are resolved relative to the current working directory. If you run `eslint` in a different working directory to the folder containing tsconfig.json, @typescript-eslint/parser will not be able to locate the file. The fix is to set a `tsconfigRootDir` to `__dirname`, which would make the parser resolve the project configuration relative to `.eslintrc.js`
Related: https://stackoverflow.com/questions/64933543/parsing-error-cannot-read-file-tsconfig-json-eslint
=> fix: tsconfig parsing error in eslintrc

package-lock.json, web/crux/package-lock.json, web/crux/package.json, web/crux/src/app/agent/agent.service.ts, web/crux/src/domain/agent.ts, web/crux/src/main.ts
Upgrading the NestJS package to 9.0.1 and the Prisma to 4.1.1
Prisma schema is still valid. 
```
➜  crux git:(fix/upgrade-prisma-nestjs) npx prisma validate                                                                                                                                     Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
The schema at ~/dyrectorio/web/crux/prisma/schema.prisma is valid 🚀
```
=> fix(crux): Upgrade Prisma and NestJS

web/crux-ui/src/components/notifications/edit-notification-card.tsx, web/crux-ui/src/components/products/versions/deployments/deployment-details-section.tsx, web/crux-ui/src/components/products/versions/images/edit-image-config.tsx, web/crux-ui/src/components/products/versions/images/edit-image-json.tsx, web/crux-ui/src/components/products/versions/images/select-images-card.tsx, web/crux-ui/src/components/shared/json-editor.tsx, web/crux-ui/src/hooks/use-throttleing.ts, web/crux-ui/src/pages/audit-log.tsx
Now json editor is scrolling vertically just fine when the config is too large for 128 rem
=> fix: json editor scrolling

web/crux-ui/locales/en/products.json, web/crux-ui/src/components/nodes/container-status-tag.tsx, web/crux-ui/src/components/products/product-details-card.tsx, web/crux-ui/src/components/products/versions/deployments/deployment-status-tag.tsx, web/crux-ui/src/components/shared/paginator.tsx, web/crux-ui/src/elements/dyo-tag.tsx, web/crux-ui/src/pages/audit-log.tsx, web/crux-ui/src/styles/global.css, web/crux-ui/tailwind.config.js
- fix(crux-ui): Hard to read DeploymentStatusTag obsolate color changed to requested 
- refactor(crux-ui): use Image instead of img in paginator and audit log
- fix(crux-ui): ProductDetailsCard layout, Changelog is display at the correct position for simple products
- feat(crux-ui): scrollbar design
=> fix(crux-ui): UI glitches

web/crux-ui/src/components/registries/edit-registry-card.tsx, web/crux-ui/src/models.ts, web/crux-ui/src/validation.ts
fix(crux-ui): clear registry fields on type change
fix(crux-ui): google registry url not mapped in edit mode
=> fix(crux-ui): clear registry fields on type change

web/crux-ui/src/components/nodes/dyo-node-setup.tsx, web/crux-ui/src/components/nodes/edit-node-card.tsx, web/crux/src/app/agent/agent.service.ts
After saving a new node you can edit it immediately and the node list stays up to date. You only have to regenerate your script if the node's name changed.
=> fix(crux-ui): node edit after save

web/crux-ui/locales/en/versions.json, web/crux-ui/src/components/layout.tsx, web/crux-ui/src/components/main/nav-button.tsx, web/crux-ui/src/components/main/sidebar.tsx, web/crux-ui/src/components/products/versions/version-deployments-section.tsx, web/crux-ui/src/elements/dyo-expandable-text.tsx
PR contains the followings:
- fix the active menu
- add padding in the version changelog when it's not too long
- add missing i18n
- format
=> fix(crux-ui): active menu and paddings fixes

agent/pkg/dagent/utils/docker.go
The previous version checked whether the container name contains the prefix or not. It lead to see containers which is contained the prefix but not necessary started with it.
=> fix(agent): use regex on container listing

agent/pkg/builder/container/container_builder.go
The deployment failed if you didn't provide any network information in the config.
=> fix(agent): fix create network

web/crux-ui/locales/en/versions.json, web/crux-ui/package-lock.json, web/crux-ui/src/components/nodes/dyo-node-card.tsx, web/crux-ui/src/components/products/versions/deployments/add-deployment-card.tsx, web/crux-ui/src/websockets/websocket-client-endpoint.ts, web/crux/src/app/agent/agent.service.ts
PR contains the following:
- Added an error toast to the create deployment screen which applies if the user wants to create more than one preparing deployment
- Fixed the issue when after you made a successful deployment the previous ones were not moved to obsolate status
- Fixed the issue when you were getting toast errors after making two simple product deployments each after
=> fix(web): deployment improvements

web/crux-ui/src/pages/audit-log.tsx
Fix for en-GB locale (dd/mm/yyyy format)
=> fix(crux-ui): auditlog datefilter

web/crux-ui/locales/en/nodes.json, web/crux-ui/locales/en/versions.json, web/crux-ui/src/components/products/versions/deployments/add-deployment-card.tsx, web/crux-ui/src/components/registries/registry-fields/v2-registry-field.tsx, web/crux-ui/src/components/shared/filters.tsx, web/crux-ui/src/pages/nodes.tsx
**Added a node status filter to node list screen.**
PR also contains additonaly the following:
- Fix missing localization on registry screen.
- Add a toast error to the add deployment screen which applies when the user has no nodes
=> feat(crux-ui): add node status filter

agent/manifest/kubernetes/deployment.yaml, agent/manifest/kubernetes/volume.yaml, web/crux/install-k8s.sh.hbr
Recent changes to secret management and end-to-end encrypted secrets need us to allocate a volume in the cluster upon the installation of crane.
=> feat: add secret volume to k8s manifests

web/crux-ui/src/pages/products/[productId]/versions/[versionId]/deployments/[deploymentId].tsx
When clicking on the deploy button while the target node is unreachable, the app shows a toast now instead of navigation to the deploy page.
=> fix: deploying on unreachable node

web/crux-ui/locales/en/versions.json, web/crux-ui/src/elements/dyo-button.tsx, web/crux/src/app/deploy/pipes/deploy.create.pipe.ts
Now you can't create deployment without having atleast one image.
PR also contains:
- fix disabled buttons
=> fix(web): restrict deployment creation without images

agent/internal/mapper/grpc.go, protobuf/proto/crux.proto, web/crux-ui/locales/en/common.json, web/crux-ui/public/circle-bright.svg, web/crux-ui/src/components/nodes/container-status-indicator.tsx, web/crux-ui/src/components/nodes/container-status-tag.tsx, web/crux-ui/src/components/products/versions/deployments/deployment-container-status-list.tsx, web/crux/proto/crux.proto, web/crux/src/app/node/node.service.ts
From now, on the deployment's log screen you can always see your containers (even if they are deleted). Previously when you started a deplyoment the container's list were uploaded continuously. Now only their status are updated. Also the prefix has been removed from the container's name in case of docker.
=> feat(web): use default container list on deployment screen

web/crux/prisma/migrations/20220929162700_use_updated_at_attribute/migration.sql, web/crux/prisma/schema.prisma, web/crux/src/app/deploy/deploy.service.ts, web/crux/src/app/image/image.service.ts, web/crux/src/app/node/node.service.ts, web/crux/src/app/notification/notification.service.ts, web/crux/src/app/product/product.service.ts, web/crux/src/app/registry/registry.service.ts, web/crux/src/app/team/team.service.ts, web/crux/src/app/version/version.service.ts
Replaces `@default(now())` with `@updatedAt` and removes all `updatedAt` in code when updating records.
> Important: This PR introduces one unwanted behavior, where new records created may have the `updatedAt` field not matching `createdAt` if wherever the database is hosted uses a different system time than the client, due to https://github.com/prisma/prisma/issues/12572.
The above unwanted behavior is tracked in #219.
Feedback is welcome!
Closes #208.
=> refactor(crux): use @updatedAt in prisma schema

cli/config_file.go, cli/runner.go
Fixes: #237 
Changes:
- Verify that exposed port from `dyrectorio` stack is available on host
- Prompt user for another port for `stack` element
- Find duplicate `external` port after changes
Demo:
- start listening on port `5432`
```bash
nc -l 5432
```
- run `dyrectorio` stack setup
```
go run . up
```
https://user-images.githubusercontent.com/25000090/193915452-f07e8d96-02c0-4a0d-b80c-dae4d8a9bb23.mov
=> feat: check open/duplicate port when fire up dyrectorio stack with cli

web/crux-ui/src/pages/teams/[teamId]/invite.tsx
Instead of error msg, redirect to 404 page when the invite is not found (invalid or unauthorized)
=> fix(crux-ui): redirect to 404 when invalid invite

README.md, golang/pkg/cli/config_file.go, golang/pkg/cli/container_defaults.go
This PR adds support to older docker for windows installations, since newer ones use WSL2; and Docker SDK still using the old method so now the Traefik's socket is configurable, and if we stay at the default and we have a DOCKER_HOST env variable in use, we prefer that.
=> fix(cli): named pipe "deprecation", add socket to configuration

golang/pkg/cli/container_defaults.go
Kratos and CruxUI connection was faulty also Traefik were exposing the wrong port when we didn't used the default. Big thanks @robot9706 for pointing out this bug!
=> fix(cli): traefik custom port

golang/internal/config/secret.go, golang/internal/config/secret_test.go
default custom headers in PGP blocks are not deterministic because their order is not fixed
so I remove them in this PR
=> fix(agent): remove comment and version strings from pgp keys

golang/pkg/builder/container/container_builder.go, golang/pkg/builder/container/utils.go, golang/pkg/cli/config_file.go, golang/pkg/cli/container_defaults.go
WithoutConflict builder function is reworked, only sets a flag, real work will happen in Create function
deleteContainer internal function now wont print errors unless it's necessary: detects running/exited containers and acts accordingly.
=> feat(agent): silence containerbuilder's WithoutConflict func, rework WithoutConflict function, extend deleteContainer function

golang/internal/crypt/pgp_test.go
Paths have changed and it might have been merged accidentally in https://github.com/dyrector-io/dyrectorio/pull/269.
=> fix: move pgp test into the correct folder

golang/.gitignore, golang/Makefile
- Issue [#155](https://github.com/dyrector-io/dyrectorio/issues/115)
Applied to two build targets: `go-crane` & `go-dagent`.
Not applied to `debug-grpc`. (reason: uncertain target purpose)
Possible Future Actions:
1. Add the graceful shutdown to `golang/internal/grpc/grpc.go:grpcLoop()` via [signal catching](https://github.com/cosmtrek/air/blob/bb7fe2887750390eee13daa25348723a5fb20308/main.go#L61-L62) method.
2. Watch with [send_interrupt=true](https://github.com/cosmtrek/air/blob/a2b8871f2ae8de60526b9f8ccc01b69fad9d138a/air_example.toml#L37-L38) on goair.
=> chore: goair for new watch tool and makefile modified (#155)

golang/pkg/cli/config_file.go, web/crux/install-docker.sh.hbr
This PR adds mingw64 support for dagent's install script.
if platform is detected as mingw64:
- ROOTLESS is true unless specified otherwise
- persistence dir is c:/srv/dagent unless specified otherwise
- socket is //var/run/docker.sock unless specified otherwise
fixed timeout issue (timeout is a GNU command not a POSIX one) 
it is taken out and exit codes will be handled bit differently:
upon stop failing it tries to kill as stop has built in timeout, we are fine with this AND if remove is unsuccessful we try to remove container forcefully
=> feat(crux): mingw64 support for dagent install script

web/crux/install-docker.sh.hbr
This change should fix out of bounds errors in the dagent install script on Ubuntu systems.
=> fix(crux): dagent install script on Ubuntu

golang/cmd/crane/crane.go, golang/cmd/dagent/dagent.go, golang/internal/config/secret.go, golang/pkg/builder/container/container_builder.go, golang/pkg/builder/container/utils.go, golang/pkg/cli/cli.go, golang/pkg/cli/config_file.go, golang/pkg/cli/container_defaults.go, golang/pkg/cli/runner.go
These changes silence containercreation with cli, includes some loglevel change in crane and dagent, finally refactored few functions to use dockerhelper.
=> refactor(cli): silence container creation and rework logging

golang/manifest/kubernetes/deployment.yaml
New distroless image needs different start params in manifest, added.
=> fix(agent): correct crane path manifests with distroless image

golang/pkg/crane/k8s/deploy_facade.go
Refactors might have confused me, but this is how this supposed to work.
=> fix(crane): use original `containerPreName` as a name for namespace

web/crux/templates/vaultwarden.json
done:
- cleaned labels
- simpler custom routing
The same domain name is required to be provided by the user. :thinking: Templating might be the way.
=> fix(crux): clean & correct labels for vaultwarden

web/crux/assets/install-script/install-k8s.sh.hbr
Old, currently missing manifest file blocks the Kubernetes agent install flow, removed.
=> fix(crane): remove old crane volume manifest

web/crux/templates/gitea.json
SSH port now may cause issues, this will be revised in a future release.
=> fix(crux): remove gitea ssh port until smarter traefik usage

web/crux/nest-cli.json, web/crux/package.json, web/crux/src/app/deploy/deploy.http.controller.ts, web/crux/src/app/image/image.http.controller.ts, web/crux/src/app/node/node.http.controller.ts, web/crux/src/app/product/product.http.controller.ts, web/crux/src/app/registry/registry.http.controller.ts, web/crux/src/app/version/version.http.controller.ts, web/crux/src/main.ts, web/crux/src/swagger/crux.dto.ts, web/crux/src/swagger/generator.ts
Currently, we are using gRPC-generated request and response objects to interact with the HTTP API. Unfortunately, Swagger API annotations only accept classes, so we need to generate classes from TypeScript interfaces created with ts-proto. Pull requests contain a generator that can create classes for Nest Swagger documentation.
Usage: To generate the DTOs, use the following command in `crux` root folder: `npm run build:dtos`. Right now it's important to note that you will need to add missing imports manually.
=> feat(crux): swagger @ApiBody({}) DTO generator

docker-compose.yaml
Dyrectorio stack's compose file has a traefik, and there was a few new labels introduced, and since there was a new service as well, traefik couldn't deduct which router connects to which service.
=> fix: dyrectorio compose traefik has missing labels

web/crux-ui/src/routes.ts, web/crux/src/app/audit/audit.http.controller.ts, web/crux/src/app/deploy/deploy.http.controller.ts, web/crux/src/app/health/health.http.controller.ts, web/crux/src/app/image/image.http.controller.ts, web/crux/src/app/node/node.global-container.http.controller.ts, web/crux/src/app/node/node.http.controller.ts, web/crux/src/app/node/node.prefix-container.http.controller.ts, web/crux/src/app/notification/notification.http.controller.ts, web/crux/src/app/product/product.http.controller.ts, web/crux/src/app/registry/registry.http.controller.ts, web/crux/src/app/storage/storage.http.controller.ts, web/crux/src/app/team/team.http.controller.ts, web/crux/src/app/template/template.http.controller.ts, web/crux/src/app/token/token.http.controller.ts, web/crux/src/app/version/version.http.controller.ts
Remove `deployments/:deploymentId/events` as it was the duplication of `/log`
Improve api docs.
=> docs(web): improve descriptions of the api

.github/workflows/image-builder.yml, golang/Makefile, images/alpine-proto/Dockerfile
This PR resolves some discrepancy around building the "builder image"
This PR resolves the chicken-egg issue in the pipeline by removing the builder image, but using a "bare" VM to install the few stuff we need and build/push/sign the image.
=> fix(ci): image builder

README.md, web/crux/README.md
PR contains:
- Link the appropriate section to CLI config
- Update the `crux/README.md`
=> docs: add CLI docs link to readme

golang/pkg/cli/cli.go, golang/pkg/cli/config_file.go, golang/pkg/cli/container_defaults.go
This PR removes the gRPC port from the dyo CLI application.
=> fix(cli): invalid gRPC port

.github/config/auto-assign.yml, .github/workflows/pr-labeler.yml
Add an action that will assign the author of the PR to the Assignees. This action should only work with non-forked repositories due to security concerns.
=> feat(ci): add auto assignes to PR

web/crux/src/app/node/node.mapper.ts
Fixes an unhandled exception in prod
```
[Nest] 19  - 05/17/2023, 10:13:05 AM   ERROR [WsExceptionFilter] Unhandled Exception
[Nest] 19  - 05/17/2023, 10:13:05 AM   ERROR [WsExceptionFilter] TypeError: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
at NodeMapper.containerStateMessageToContainerMessage (/app/dist/app/node/node.mapper.js:54:35)
at /app/dist/app/node/node.service.js:162:110
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
at Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28 …
```
=> fix(crux): nullpointer in ContainerStateMessage mapping

web/crux/src/app/agent/agent.service.ts, web/crux/src/main.ts, web/crux/src/shared/grpc-node-connection.spec.ts, web/crux/src/shared/grpc-node-connection.ts
Take proxy headers into account while determining the address of a node.
=> feat(crux): use proxy headers to determine the node ip

.github/workflows/full.yml, .github/workflows/pipeline_set_output_tag.sh
This PR makes it possible to add another tag when we build a tagged version. The new tag is always a minor version(patchversion stripped) and will be a moving tag like latest/stable.
=> feat(ci): minor versions should always point at the latest patchversion

golang/internal/mapper/grpc.go
The problem was that from gRPC when parsing it `field.toString` function create capitalized strings that is not valid as a docker log option.
=> fix(dagent): correct logDriver mapping

web/crux-ui/src/components/storages/edit-storage-card.tsx, web/crux/src/app/deploy/deploy.mapper.spec.ts, web/crux/src/app/deploy/deploy.mapper.ts
Added default https, untouched if http or https defined, tests included.
=> fix(crux): add https if protocol is missing from storage URL

web/crux-ui/e2e/utils/projects.ts, web/crux-ui/playwright.config.ts, web/crux-ui/src/components/projects/edit-project-card.tsx, web/crux-ui/src/pages/deployments.tsx, web/crux-ui/src/pages/nodes/[nodeId].tsx, web/crux-ui/src/pages/projects.tsx, web/crux/prisma/schema.prisma
PR contains the following improvement: When the user creates a new project, now the platform navigates to the project detail page instead of the project list page.
=> fix: project creation navigation, remove playwright retries, small fixes

web/crux-ui/locales/en/nodes.json
Some reasoning and explanation and suggestion to use absolute paths, since envs and symbols can cause difficulties.
=> feat(web): add extra explanation to dagent persistence section

Makefile
The golang version.go change was left out.
=> build: include golang version change in release script

.github/workflows/product_builder.yaml
Golang images push job is now skipped because it is executed too early.
=> build(ci): add missing go_push requirement

golang/internal/helper/image/image.go
Docker hangs until its response is read, dumping all the unread bytes solves the issue.
=> fix(dagent): discard image pull response if not read

golang/build/Dockerfile
Our crane could not be installed because of this collision. Now the image can be run with parameters (again).
=> fix(agent): change agent start directive from CMD to ENTRYPOINT

golang/pkg/dagent/utils/init_container.go
Entrypoint and command mapping into init containers was missing.
=> fix(dagent): correct entrypoint and cmd for init containers

.github/workflows/deploy_external.yaml
This is an attempt of dogfooding, where we use github actions to trigger our CD for rolling version, where we update a remotely deployed dyrector.io :pizza:
=> cicd: add deploy_external workflow for external webhooks & sundyo

web/crux/src/app/audit/audit.http.controller.ts, web/crux/src/app/dashboard/dashboard.http.controller.ts, web/crux/src/app/deploy/deploy.http.controller.ts, web/crux/src/app/image/image.http.controller.ts, web/crux/src/app/metrics/metrics.controller.ts, web/crux/src/app/node/node.global-container.http.controller.ts, web/crux/src/app/node/node.http.controller.ts, web/crux/src/app/node/node.prefix-container.http.controller.ts, web/crux/src/app/notification/notification.http.controller.ts, web/crux/src/app/project/project.http.controller.ts, web/crux/src/app/registry/registry.http.controller.ts, web/crux/src/app/storage/storage.http.controller.ts, web/crux/src/app/team/team.http.controller.ts, web/crux/src/app/team/user.http.controller.ts, web/crux/src/app/template/template.http.controller.ts, web/crux/src/app/token/token.http.controller.ts, web/crux/src/app/version/version.http.controller.ts
We use the built-in Nest.js HttpStatus enums as @HttpCode parameters instead of magic numbers.
=> refactor(crux): refactor http response status codes for request handlers

web/crux/src/app/deploy/deploy.dto.ts
Fix an issue where you can't make a deployment token, because the name validation was wrong.
=> fix(crux): deployment token name validation

web/crux-ui/src/components/team/user-role-action.tsx, web/crux-ui/src/pages/projects/[projectId].tsx
Change the color of the confirm button to warning instead of error.
=> fix(crux-ui): change confirm button color

web/crux-ui/src/components/projects/project-view-list.tsx, web/crux-ui/src/components/projects/versions/version-deployments-section.tsx, web/crux-ui/src/pages/deployments.tsx, web/crux/src/app/deploy/deploy.dto.ts
- Fixed view buttons were missing from the deployments list rows.
- Fixed project list rows were not clickable to view them (similarly to the deployment list rows).
- Fixed version deployment list rows were not clickable to view them (similarly to the deployment list rows).
=> fix(crux-ui): add view buttons to deployment list rows

golang/internal/helper/docker/container.go, golang/internal/helper/string.go, golang/internal/helper/string_test.go, golang/pkg/dagent/utils/docker.go, golang/pkg/dagent/utils/traefik.go, golang/pkg/dagent/utils/traefik_test.go
In dagent if no enough config provided: no domain, nor env variable the Host rule is omitted.
If Expose is set but no prefix or domain is provided, it error is thrown by the deployment.
=> fix(dagent): remove host Rule if no root domain is given

golang/internal/health/server.go, golang/internal/health/types.go, golang/pkg/crane/config/config.go, golang/pkg/crane/crane.go, golang/pkg/crane/k8s/namespace.go, web/crux/assets/install-script/install-k8s.sh.hbr
Launching crane as a pod proved to be wrong, reverting to deployment.
=> refactor(crane): use deployment, add RBAC changes

web/crux-ui/src/websockets/websocket-client-route.ts, web/crux-ui/src/websockets/websocket-client.ts, web/crux/src/app/deploy/deploy.http.controller.ts, web/crux/src/app/deploy/deploy.service.ts, web/crux/src/app/deploy/deploy.ws.gateway.ts
- Use the `routes` map on client side websocket to route messages.
- Fix deployment environment editing
=> refactor(web): optimize ws client routing

golang/internal/config/secret.go
Fixes an issue, where reinstalling an agent for a different backend (issuer) caused a crash. Now we prefer the environment supplied grpc token over the saved one on issuer mismatch.
=> fix(agent): crashing on install and connection token mismatch

web/crux/src/app/audit/audit.mapper.ts, web/crux/src/app/audit/audit.service.ts, web/crux/src/services/kratos.service.ts, web/crux/src/shared/const.ts
Fix an issue with the audit log, where the `KratosService` was not able to provide user info after the 250th user.
=> fix: kratos user list pagination

web/crux-ui/e2e/utils/test.fixture.ts, web/crux-ui/e2e/utils/websocket-match.ts, web/crux-ui/e2e/with-login/deployment/deployment-copy.spec.ts, web/crux-ui/e2e/with-login/deployment/deployment-copyability-versioned.spec.ts, web/crux-ui/src/components/deployments/add-deployment-card.tsx, web/crux-ui/src/components/projects/versions/deployments/add-deployment-to-version-card.tsx, web/crux-ui/src/components/projects/versions/version-sections.tsx, web/crux/src/app/deploy/deploy.service.ts
Now while copying a deployment id only copies the secrets, when the target is the same node.
Add e2e tests for the two upper mentioned cases.
=> fix: copying a deployment now does not copies the secret values to a different node

web/crux/assets/install-script/install-k8s.sh.hbr
This removes a duplication and add the correct name for PVCs for cranes aggregated read-only cluster role.
=> fix(crane): rename clusterrole RBAC in install script

.github/workflows/product_builder.yaml, golang/.gitignore, golang/Makefile, golang/pkg/builder/container/container_builder_integration_test.go, golang/pkg/crane/k8s/deploy_facade.go, golang/pkg/crane/k8s/deployment.go, golang/pkg/crane/k8s/deployment_integration_test.go, golang/pkg/dagent/update/update_integration_test.go
We have not sent all the golang test results to **codecov**, addressing this in this PR.
=> cicd: add more coverage files, to display a more valid number

golang/internal/helper/image/image_unit_test.go, golang/internal/pointer/pointer.go, golang/internal/pointer/pointer_test.go
Fixes #832
Unit tests were spread across various functions, but most of them can be organized into table driven test cases.
=> refactor: internal/helper/image_unit_test : use table driven tests

golang/internal/helper/image/image.go, golang/internal/helper/image/image_unit_test.go
We found that on GitHub the organization can have uppercase letters, but the images on ghcr.io will not have uppercase, as per standards.
[Specs](https://github.com/moby/moby/blob/master/image/spec/spec.md).
=> fix(agent): add capital image name handling

.github/workflows/product_builder.yaml
Add back the `product_builder.yaml` to the `gather_changes` job.
=> cicd: restore pipeline change tracking

web/crux-ui/src/components/registries/registry-fields/github-registry-field.tsx, web/crux-ui/src/components/registries/registry-fields/gitlab-registry-field.tsx, web/crux-ui/src/components/registries/registry-fields/google-registry-field.tsx, web/crux-ui/src/components/registries/registry-fields/hub-registry-fields.tsx, web/crux-ui/src/components/registries/registry-fields/v2-registry-field.tsx, web/crux-ui/src/components/storages/edit-storage-card.tsx
Hide the change credentials toggle, while creating a registry or a storage
=> fix(crux-ui): hide change credentials field when creating a registry or a storage

web/crux/src/app/image/image.service.ts
Fix an internal server error, when trying to select a tag for a newly added image.
=> fix(crux): crash while selecting tag for images without an environment

web/crux-ui/locales/en/pipelines.json, web/crux-ui/src/components/pipelines/edit-event-watcher-card.tsx, web/crux-ui/src/components/pipelines/trigger-pipeline-card.tsx, web/crux-ui/src/components/pipelines/use-pipeline-state.ts, web/crux-ui/src/models/pipeline.ts, web/crux/src/domain/pipeline.ts, web/crux/src/services/azure-devops.service.ts
Fixes:
- Inaccurate label on `TriggerPipelineCard`
- Duplicated runs after triggering a pipeline
- Azure pipeline variable declarations
Feat:
- Show azure's error message, when manual triggering fails.
=> fix: pipeline related bugs

golang/pkg/cli/cli.go, golang/pkg/cli/generate.go
Added command so that it could be called as:
```
docker run --rm ghcr.io/dyrector-io/dyrectorio/cli/dyo:latest generate crux encryption-key
```
This could be used to generate commands, also this could be extended for other similar variables.
=> feat(cli): add frontend for crux encryption-key generation

web/crux/crux-docker-entrypoint.sh, web/crux/src/config/app.config.ts
Fixes an issue, where one could not generate an encryption key without defining the `ENCRYPTION_SECRET_KEY` variable.
=> fix(crux): encryption key generation

web/crux/.env.example
The file itself is linked to the docs, so `.env.example` files have to be descriptive, since they serve as living documentation.
=> doc(crux): add extra info encrpytion gey generation

web/crux-ui/src/components/main/nav-button.tsx
Now the active item is highlighted on the side-menu again.
=> fix(crux-ui): active menu

web/crux-ui/src/components/nodes/node-containers-list.tsx
Add  a tooltip for the container names in node container list
=> feat(crux-ui): add tooltip for container names in node container list

web/crux-ui/src/components/projects/versions/deployments/instances/use-instance-state.ts, web/crux-ui/src/components/shared/secret-key-value-input.tsx
Fixes an issue where adding a secret to the instance config overwrites the exiting ones.
=> fix(crux-ui): overwritten deployment secrets

.env.example
Missing the `ENCRYPTION_SECRET_KEY` key from the root `.env.example`, fixed this.
=> fix: add ENCRYPTION_SECRET_KEY to root .env.example

web/crux/src/app/node/node.container.http.controller.ts
As the title says, extend the API GET log with a global container description.
=> fix(crux): improve log API description

web/crux/src/domain/agent.ts
Fixes an issue, where the agent status was reported as `connected` too early, while the install token was still replacing.
=> fix(crux): agent token replacement status

web/crux/.env.example, web/crux/src/app/node/node.dto.ts, web/crux/src/config/app.config.ts, web/crux/src/main.ts
Add `MAX_GRPC_RECEIVE_MESSAGE_LENGTH` env variable
=> feat(crux): add an env to set grpc maxReceiveMessageLength

golang/internal/grpc/grpc.go, web/crux-ui/src/models/node.ts, web/crux-ui/src/pages/[teamSlug]/nodes/[nodeId]/log.tsx, web/crux/package-lock.json, web/crux/src/app/node/node.container.ws.gateway.ts, web/crux/src/app/node/node.message.ts, web/crux/src/app/node/node.service.ts, web/crux/src/domain/agent-tunnel.ts, web/crux/src/domain/agent.spec.ts, web/crux/src/domain/agent.ts, web/crux/src/domain/container-log-stream.ts, web/crux/src/shared/fixed-length-linked-list.ts
- Refactor container log stream handling on web
- Fix microtasking in go
=> refactor: container log stream

web/crux/src/app/deploy/deploy.service.ts
Fixes the endpoint `/deployments/:deploymentId/instances/:instanceId` to return the instance config as it supposed to.
=> fix(crux): get instance config

golang/internal/helper/image/image.go, golang/pkg/builder/container/utils.go
Resolves a go lint issue with the deprecated `types.AuthConfig`
=> fix(agent): deprecated types.AuthConfig

web/crux-ui/Dockerfile
Since **wget** defaults to IPv6 it causes healthcheck to fail, binding dualstack in crux-ui, as it is done in crux addresses the issue.
=> fix(crux-ui): add IPv6 listen for dual-stack listening

web/crux-ui/src/components/composer/compose-environment.tsx, web/crux-ui/src/components/composer/use-composer-state.ts, web/crux-ui/src/models/compose.ts, web/crux-ui/src/pages/composer.tsx, web/crux-ui/src/validations/compose.ts
Now the composer includes all the environment values from the .env file
=> fix(crux-ui): compose env_file apply

web/crux-ui/src/components/composer/use-composer-state.ts, web/crux-ui/src/models/compose.ts
- Environment values containing a `=` sign is now being parsed correctly
- Default to rwo for volumes without a type
=> fix(crux-ui): envs split only at the first equals sign

.golangci.yml, Makefile
Two minor things:
The `make release` command if executed on different machines ignored the remote tags, because they are not pulled by the script.
The other one addresses a deprecation notice in the golangci configuration.
=> chore: more consistent release generation, adjust lint config

web/crux-ui/src/components/projects/versions/images/config/common-config-section.tsx, web/crux-ui/src/validations/common.ts, web/crux-ui/src/validations/container.ts
Using 'unsafe' environment keys now only shows a warning instead of a blocking error.
=> fix(crux-ui): secret releated env keys

go.mod, go.sum, golang/internal/runtime/container/container.go, golang/internal/runtime/container/container_test.go
Installing dagent on a RHEL based distribution is not possible because `serverversion is not supported`. The PR addresses the problem.
=> fix(dagent): change version check to accept version with metadata

golang/internal/helper/image/image.go, golang/internal/helper/image/image_unit_test.go
Uppercase letters in image names are not valid, however tags **can** be.
=> fix(agent): add support for mixed-case image tags

web/crux/src/app/image/image.http.controller.ts, web/crux/src/app/image/pipes/image.add.pipe.ts
As the title says, we have a lack of validation in the `/api/$/projects/$/versions/$/images` API route.
=> feat: add validation to /api/$/projects/$/versions/$/images API

golang/internal/util/string.go, golang/internal/util/string_test.go, golang/pkg/dagent/utils/docker.go
I just ran into the issue where I wanted to override an environment variable with an empty string and it was not working properly. The change addresses the issue.
=> fix(dagent): adjust of env variables, empty string as valid value

golang/internal/config/config.go, web/crux/.env.example, web/crux/src/config/app.config.ts, web/crux/src/main.ts
Using Cloudflare, the default 100 seconds timeout applied causing agents to disconnect every 100 minute.
The change puts reasonable lower keepalive number for both client and server side to address the issue.
=> fix: add client & server side keepalive

package-lock.json, web/crux/package-lock.json, web/crux/package.json, web/crux/src/app/container/container.mapper.ts, web/crux/src/app/registry/registry-client.provider.ts, web/crux/src/app/registry/registry.mapper.ts, web/crux/src/interceptors/prisma-error-interceptor.ts
Override the original `nestjs-modules/mailer` due to a vulnerability issue. Added a small formatting fix based on the updated Prettier.
=> fix: override nestjs-modules/mailer with new mjml version

.env.example, .github/workflows/builder_image_multidb.yaml, distribution/images/multi-db/.env.example, distribution/images/multi-db/Dockerfile, distribution/images/multi-db/docker-compose.yml, distribution/images/multi-db/init-database.sh, docker-compose.yaml, web/crux/.env.example, web/crux/docker-compose.yaml
We had two PostgreSQL instances instead of one. This PR merges them into a single instance and refactors the `docker-compose.yaml` files accordingly.  
I skipped the `cli` refactor because, after discussing with the internal team, we decided to use `docker compose` instead of the `CLI`.
=> feat(web): merge postgress instances

Makefile, golang/Makefile, golang/pkg/cli/.gitignore, golang/pkg/cli/setup/setup.go, repo_root.go
Duplicated off-tree compose files caused issues and it's not particularly neat. This is a proposal of an alternative solution to avoid duplication.
=> refactor(cli): avoid compose file duplication
