dyrector-io/dyrectorio

web/crux-ui/src/elements/dyo-list.tsx
web/crux-ui/src/pages/teams/active.tsx
web/crux-ui/src/pages/teams/audit-log.tsx

fix: Expand the Name and Date column in Audit Log view
feat: Make a readonly json editor in the popup modal
refactor: dyo-list component to use table layout

fix(crux-ui): Auditlog Improvements

---

.editorconfig
.gitattributes
CONTRIBUTING.md

Done:
- Updated CONTRIBUTING.md file
- Added .editorconfig and .gitattributes for all languages in use

chore: contributing update, editorconfig and gitattributes

---

web/crux/install-k8s.sh.hbr

Change the wrong manifest URL paths in the Kubernetes install script template and delete unused `INGRESS_ROOT_DOMAIN` env.

fix: change the manifest paths

---

web/crux/Dockerfile

Rename the install script files.

fix: rename the install script files

---

web/crux-ui/locales/en/common.json
web/crux-ui/src/components/nodes/dyo-node-card.tsx
web/crux-ui/src/components/nodes/node-status-indicator.tsx

running color fixed and added address label

fix: node card content

---

web/crux-ui/locales/en/common.json
web/crux-ui/locales/en/images.json
web/crux-ui/locales/en/versions.json
web/crux-ui/src/components/products/versions/images/edit-image-card.tsx
web/crux-ui/src/components/products/versions/version-deployments-section.tsx

fix: missing locales
fix: deployment status tag size

fix: missing locales

---

web/crux-ui/.env.example
web/crux-ui/docker-compose.yaml
web/crux-ui/src/pages/auth/login.tsx
web/crux-ui/src/pages/auth/recovery.tsx
web/crux-ui/src/pages/auth/register.tsx
web/crux-ui/src/pages/auth/verify.tsx
web/crux-ui/src/server/crux/crux.ts

Rename NEXT_PUBLIC_RECAPTCHA_SITE_KEY to RECAPTCHA_SITE_KEY
This env now _runtime_ instead of _build time_

refactor: runtime recaptcha site key env

---

agent/internal/grpc/grpc.go

Traefik things, this needs more insight.

fix: removing 443 when 443 and https both given

---

web/crux-ui/.env.example
web/crux-ui/.gitignore
web/crux-ui/README.md
web/crux-ui/e2e/common.ts
web/crux-ui/e2e/login.spec.ts
web/crux-ui/package-lock.json
web/crux-ui/package.json
web/crux-ui/playwright.config.ts

techdept: add e2e tests

---

web/crux-ui/src/components/shared/json-editor.tsx

I just changed the caret color to white (the basic color was not well visible)

chore: json editor better caret color for visibility

---

agent/go.mod
agent/go.sum
agent/internal/config/config.go
agent/internal/grpc/grpc.go
agent/pkg/builder/container/utils.go

Had a quick look on imagePull, we read the progress slowly and the visual caused delay.
Also I've added some small improvements around grpc.

fix(agent): image pull throttle, package updates, style

---

web/crux-ui/playwright.config.ts
web/crux-ui/src/components/nodes/dyo-node-setup.tsx
web/crux-ui/src/components/products/versions/use-images-websocket.ts
web/crux-ui/src/components/shared/sh-editor.tsx

implement sh editor and minor ui fixes
chore(crux-ui): run prettier

fix(crux-ui): node setup script improvement

---

web/crux-ui/src/components/nodes/edit-node-card.tsx
web/crux-ui/src/validation.ts
web/crux/prisma/migrations/20220829085939_restrict_name_text_length/migration.sql
web/crux/prisma/schema.prisma

Limit number of characters allowed in name text field [Deployment, Node, Notification, Product, Registry, Team, Version]: (min:3, max:70)

fix: restrict name text length

---

web/crux-ui/src/components/layout.tsx
web/crux-ui/tailwind.config.js

The error toast was white because of a wrong style.

fix(crux-ui): white error toast

---

web/crux-ui/src/components/products/versions/deployments/deployment-events-terminal.tsx
web/crux/src/app/deploy/deploy.mapper.ts

PR contains the following:
- Error fixed on deployment's log screen
- Deployment log's terminal has fixed hight now

fix(crux): fix deployment log

---

agent/pkg/builder/container/container_builder.go

Using our builder in #100 turned out that we need better checks.

fix(agent): dagent network creation condition corrected

---

web/crux-ui/locales/en/registries.json
web/crux-ui/src/components/registries/edit-registry-card.tsx
web/crux-ui/src/components/registries/registry-fields/gitlab-registry-field.tsx
web/crux-ui/src/components/registries/registry-fields/google-registry-field.tsx
web/crux-ui/src/components/registries/registry-fields/v2-registry-field.tsx
web/crux-ui/src/models.ts
web/crux-ui/src/server/crux/registry-service.ts
web/crux-ui/src/server/registry-api/registry-connections.ts

Changed "Invalid Argument" error to "Registry with the given URL doesn’t exist"

feat(crux-ui): change registry url error

---

web/crux-ui/locales/en/versions.json
web/crux-ui/src/components/layout.tsx
web/crux-ui/src/components/products/versions/edit-version-card.tsx
web/crux-ui/src/components/products/versions/increase-version-card.tsx
web/crux-ui/src/components/shared/page-heading.tsx
web/crux-ui/src/hooks/use-version-hint.ts
web/crux-ui/src/validation.ts

fix(crux-ui): Version semantic hint
fix(crux-ui): Large gap on the right side of the main layout
fix(crux-ui): Not consistent breadcrumb header positions

fix(crux-ui): version hint

---

web/crux/prisma/seeds/data/demo/container_config.ts
web/crux/prisma/seeds/data/demo/registry.ts
web/crux/prisma/seeds/demo-seeder.ts

fix(crux): demo seeder missing fields

---

web/crux-ui/locales/en/common.json
web/crux-ui/src/elements/dyo-date-picker.tsx
web/crux-ui/src/pages/audit-log.tsx
web/crux-ui/src/utils.ts

Audit log date filter and details modal dates fixed

fix(crux-ui): date inconsistency

---

web/crux-ui/src/components/nodes/dyo-node-version-text.tsx

Added "unknown version" text in case there is no version

fix(crux-ui): node tooltip

---

agent/internal/config/secret.go

Fix contains the followings:
- We have to check the `EISDIR` error and added the missing error check from `os.ReadFile()`
- Rename `location` to `path`

fix: check directory for secret keys

---

web/crux-ui/package.json

command 'format' not working on windows
use npm run format:win32

feat(crux-ui): prettier format on windows

---

web/crux/package-lock.json
web/crux/package.json

Upgraded `@prisma/client` to `4.4.0` to fix the unwanted behavior introduced by #225.
Closes #219.

chore(crux): upgrade prisma client version to 4.4.0

---

CHANGELOG.md
web/crux-ui/package.json
web/crux/docker-compose.yaml
web/crux/package.json
web/crux/prisma/schema.prisma

Fixes a segfault within the crux container image, which occurred with ssl based db connections.

fix: prisma segfault

---

agent/pkg/builder/container/exec_builder.go
cli/config_file.go

Fixing CI first before adding more PR.

chore: fix broken CI - lint/security @ b5abab4

---

CHANGELOG.md
agent/api/v1/deploy_test.go
agent/internal/util/json.go
agent/internal/util/json_test.go

- Add unit tests for the agent/api pkg.
- Fixed wrong argument order in JSON unit test.
- util.RemoveJSONComment now also removes trailing spaces and tabs.
Part of #241

refactor(test): add unit tests for agent/api

---

README.md

chore: update readme with cli changes, add additional instructions

---

web/crux-ui/package.json

This should solve the issue raised in https://github.com/dyrector-io/dyrectorio/issues/224

fix(crux-ui): npm install target script

---

agent/pkg/crane/k8s/clients.go
agent/pkg/crane/k8s/clients_test.go
agent/pkg/crane/k8s/configmap.go
agent/pkg/crane/k8s/deployment.go
agent/pkg/crane/k8s/ingress.go
agent/pkg/crane/k8s/namespace.go
agent/pkg/crane/k8s/pvc.go
agent/pkg/crane/k8s/secret.go
agent/pkg/crane/k8s/service.go

This PR also aims to achieve https://github.com/dyrector-io/dyrectorio/issues/241 goals testing crane/k8s/clients.go

refactor(test): add unit test for crane clients

---

golang/pkg/cli/config_file.go

Thanks for the bughunt @D3vl0per !

fix(cli): config dir creation

---

.gitignore
README.md
agent/internal/crypt/pgp_test.go

* add unit test for agent/internal/crypt
* fixed typo in readme
related to #241

refactor(test): add unit tests for agent/internal/crypt

---

.vscode/launch.json

I've noticed these remained old, I might've stashed these instead of committing.

chore: actualize vscode debug paths

---

web/crux/src/app/deploy/deploy.mapper.ts
web/crux/src/app/deploy/deploy.service.ts
web/crux/src/app/template/template.service.ts
web/crux/src/shared/validation.ts
web/crux/templates/google-microservices.json

fix(web): fix minor deploy and template bugs

feat(web): create grc microservices template

---

golang/manifest/kubernetes/deployment.yaml

#245, https://github.com/dyrector-io/dyrectorio/pull/293 Related

feat(agent): #245, crane init at k8s deployment for shared secret

---

golang/internal/mapper/grpc_test.go

refactor(test): Add unit tests for golang/internal/mapper

---

web/crux/src/app/template/template.service.ts
web/crux/src/services/template.file.service.ts
web/crux/templates/strapi.json

From now you can add your secrets to the template.

feat(crux): add secrets to template

---

web/crux-ui/locales/en/common.json
web/crux-ui/locales/en/deployments.json
web/crux-ui/src/components/products/versions/version-deployments-section.tsx
web/crux-ui/src/hooks/use-websocket-translation.ts
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/deployments/[deploymentId].tsx
web/crux/src/app/deploy/deploy.service.ts

feat(crux-ui): add websocket translation
fix(crux-ui): deployment ui fixes
fix(crux-ui): start deployment only navigated to the log screen

feat(crux-ui): add websocket translation

---

web/crux/Dockerfile

Pipeline is broken, here is the solution :cat2:

fix(crux): remove cert related code from Dockerfile

---

golang/cmd/crane/crane.go
golang/cmd/dagent/dagent.go
golang/internal/config/secret.go
golang/pkg/crane/k8sconfig/secret.go
golang/pkg/dagent/config/secret.go
web/crux-ui/e2e/image-config.spec.ts
web/crux-ui/locales/en/container.json
web/crux-ui/src/components/nodes/dyo-node-card.tsx
web/crux-ui/src/components/products/versions/images/config/common-config-section.tsx
web/crux-ui/src/components/products/versions/images/config/crane-config-section.tsx
web/crux-ui/src/components/products/versions/images/config/dagent-config-section.tsx
web/crux-ui/src/components/products/versions/images/image-config-filters.tsx
web/crux-ui/src/components/products/versions/version-view-list.tsx
web/crux-ui/src/hooks/use-confirmation.ts
web/crux-ui/src/hooks/use-websocket-translation.ts
web/crux-ui/src/models/image.ts
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/deployments/[deploymentId].tsx
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/image/[imageId].tsx
web/crux/src/app.module.ts
web/crux/src/interceptors/common-error-interceptor.ts
web/crux/src/services/domain.notification.service.ts

fix(agent): inject secret key
fix(crux-ui): confirmation modal cancel fix
fix(crux-ui): deployment delete navigate
fix(crux-ui): image config sections improvements
fix(crux-ui): image list actions responsive display
feat(crux-ui): add back btn to image details
fix(crux-ui): node status indicator position center
fix(crux): add common error interceptor

fix: minor fixes 

---

.github/workflows/golang.yml
.github/workflows/web-crux-ui.yml
.github/workflows/web-crux.yml
.github/workflows/web-kratos.yml
Makefile
images/proto/Dockerfile

Some binaries were left out accidentally from the docker image.

fix: add proto image missing binaries

---

web/crux/.env.example
web/crux/package-lock.json
web/crux/package.json
web/crux/src/app.module.ts
web/crux/src/app/agent/agent.controller.ts
web/crux/src/app/agent/agent.module.ts
web/crux/src/app/agent/agent.service.ts
web/crux/src/app/audit/audit.controller.ts
web/crux/src/app/deploy/deploy.controller.ts
web/crux/src/app/health/health.controller.ts
web/crux/src/app/image/image.controller.ts
web/crux/src/app/metrics/metrics.controller.ts
web/crux/src/app/node/node.controller.ts
web/crux/src/app/notification/notification.controller.ts
web/crux/src/app/notification/notification.module.ts
web/crux/src/app/product/product.controller.ts
web/crux/src/app/registry/registry.controller.ts
web/crux/src/app/team/team.controller.ts
web/crux/src/app/template/template.controller.ts
web/crux/src/app/version/version.controller.ts
web/crux/src/interceptors/audit-logger.interceptor.ts
web/crux/src/interceptors/grpc.error.interceptor.ts
web/crux/src/interceptors/grpc.logger.interceptor.ts
web/crux/src/interceptors/http.logger.interceptor.ts
web/crux/src/interceptors/prisma-error-interceptor.ts
web/crux/src/main.ts

Add Prometheus with an agent connection counter.

feat(crux): add Prometheus basics

---

golang/cmd/crane/crane.go
golang/cmd/dagent/dagent.go
golang/pkg/crane/k8s/deploy_facade.go
golang/pkg/crane/k8s/deployment.go
golang/pkg/crane/k8s/secret.go

crane needs docker registry authentication, here it comes.

feat(agent): add registry authentication to crane

---

golang/cmd/crane/crane.go
golang/internal/config/config.go
golang/pkg/crane/config/config.go
golang/pkg/dagent/config/config.go
golang/pkg/dagent/utils/docker.go

Add missing `setValue()` `godocs`, please @nandor-magyar review.

chore(agent): add missing setValue() docs

---

web/crux-ui/e2e/nodes.spec.ts
web/crux/install-docker.sh.hbr

Pull request contains: 
- Remove unnecessary `rootPath.fills` in test
- Add `(~)` to path
- Add logs for containers (more verbosity)
- Refactor `HOST_DOCKER_SOCK_PATH`

fix: agent install paths for OSs

---

web/crux-ui/e2e/deployment-copibility.spec.ts
web/crux-ui/e2e/deployment.spec.ts
web/crux-ui/e2e/utils/products.ts
web/crux/src/app/deploy/deploy.service.ts
web/crux/src/app/deploy/pipes/deploy.copy.pipe.ts

fix(web): multi prefix preparing deployment copy

---

web/crux-ui/src/server/crux/mappers/image-mappers.ts
web/crux/install-docker.sh.hbr
web/crux/src/app/image/image.mapper.ts
web/crux/src/app/template/template.service.ts
web/crux/src/shared/models/container.ts

fix(crux): volume and ingress upload limit fix
fix: docker install script (windows path config and persistence folder)

fix: mapper and docker install script fix 

---

golang/cmd/crane/crane.go
golang/internal/mapper/grpc.go
golang/pkg/crane/crux/deploy.go
golang/pkg/crane/crux/deploy_test.go
golang/pkg/crane/k8s/delete_facade.go
golang/pkg/crane/k8s/deploy_facade.go
golang/pkg/crane/k8s/deployment.go
golang/pkg/crane/k8s/namespace.go
golang/pkg/crane/k8s/service.go
golang/pkg/dagent/config/config.go
web/crux/src/app/agent/agent.service.ts

Done:
- create namespace if not exists
- list all deployments/services if namespace is not provided // ports are not yet functional though

fix(agent): add crane deployment list all namespaces

---

web/crux-ui/src/components/products/versions/deployments/deployment-events-terminal.tsx
web/crux-ui/src/components/products/versions/deployments/use-deployment-state.tsx
web/crux-ui/src/models/deployment.ts
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/deployments/[deploymentId].tsx

Fix deployment deploy and log functionality.
Also resize the deployment event window.

fix(crux-ui): deployment deploy and log

---

golang/Makefile
golang/build/Dockerfile
golang/pkg/dagent/utils/docker.go

new: 
- distroless agent image
- absolute path support for mounts

feat(agent): distroless image, abs path support for mounts

---

web/crux-ui/e2e/template.spec.ts
web/crux/templates/link-ace.json

feat: add LinkAce template

---

package-lock.json
web/crux-ui/src/components/nodes/edit-node-card.tsx
web/crux-ui/src/components/notifications/edit-notification-card.tsx
web/crux-ui/src/components/products/edit-product-card.tsx
web/crux-ui/src/components/products/versions/deployments/edit-deployment-card.tsx
web/crux-ui/src/components/products/versions/edit-version-card.tsx
web/crux-ui/src/components/products/versions/increase-version-card.tsx
web/crux-ui/src/components/registries/edit-registry-card.tsx
web/crux-ui/src/components/shared/secret-key-value-input.tsx
web/crux-ui/src/components/team/create-team-card.tsx
web/crux-ui/src/components/team/edit-team-card.tsx
web/crux-ui/src/components/team/invite-user-card.tsx
web/crux-ui/src/components/templates/apply-template-card.tsx
web/crux-ui/src/elements/dyo-file-upload.tsx
web/crux-ui/src/elements/dyo-form.tsx
web/crux-ui/src/elements/dyo-input.tsx
web/crux-ui/src/elements/dyo-text-area.tsx
web/crux-ui/src/pages/auth/login.tsx
web/crux-ui/src/pages/auth/recovery.tsx
web/crux-ui/src/pages/auth/register.tsx
web/crux-ui/src/pages/auth/settings/change-password.tsx
web/crux-ui/src/pages/auth/settings/edit-profile.tsx
web/crux-ui/src/pages/auth/settings/no-password.tsx
web/crux-ui/src/pages/auth/verify.tsx

- dyo input id
- dyo text area id

feat(crux-ui): add form submit to ctrl+enter

---

web/crux/templates/minecraft.json

It works but can be improved with other configurations

feat: add minecraft server template

---

golang/pkg/crane/k8s/deployment.go

Initially we had the incentive to force allocation of every request and limit (CPU and memory). Regarding memory this can be considered a successful practice, but overall machine CPU time could be used more efficiently if services in need could utilize otherwise available CPU capacity.

feat(agent): add option not to have CPU limits

---

web/crux-ui/src/models/editor.ts
web/crux-ui/src/pages/auth/settings/edit-profile.tsx

Pull request fixes the name creation error if the user adds whitespace to their name.

fix(crux-ui): name creation

---

go.mod
golang/Makefile
web/crux-ui/src/components/products/versions/deployments/instances/use-instance-state.ts
web/crux-ui/src/components/products/versions/images/config/common-config-section.tsx
web/crux-ui/src/components/products/versions/images/config/crane-config-section.tsx
web/crux-ui/src/components/products/versions/images/config/dagent-config-section.tsx
web/crux-ui/src/components/products/versions/images/image-config-filters.tsx
web/crux-ui/src/models/image.ts
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/deployments/[deploymentId]/instance/[instanceId].tsx
web/crux-ui/src/pages/products/[productId]/versions/[versionId]/image/[imageId].tsx
web/crux/src/app/agent/agent.service.ts
web/crux/src/app/deploy/deploy.mapper.ts
web/crux/src/app/deploy/deploy.service.ts

Testing revealed some issues, here are the fixes forged with @m8vago .
While testing templates found some issues:
- exposing strategy selection was not visible
- default instance view was filtered (ninja fields)
@robot9706 @polaroi8d please check!

fix: fix config mapping, default filters

---

web/crux-ui/locales/en/common.json
web/crux-ui/locales/en/register.json
web/crux-ui/src/pages/auth/register.tsx

fix(crux-ui): add privacy to registry screen

---

golang/manifest/kubernetes/deployment.yaml
web/crux-ui/package-lock.json
web/crux-ui/src/components/products/versions/images/config/common-config-section.tsx
web/crux-ui/src/validations/container.ts
web/crux/package-lock.json
web/crux/src/app/image/image.mapper.ts
web/crux/src/app/template/template.service.ts
web/crux/src/shared/validation.ts
web/crux/templates/cal-com.json
web/crux/templates/gitea.json
web/crux/templates/linkace.json
web/crux/templates/strapi.json

Cal.com:
- resource-config
- ReadWrite volume is requested
- DB url corrected
- DB internal expose for verbosity (crane does need it)

fix(crux): various fixes and refinements of templates

---

.env.example
docker-compose.yaml

This Pull request adds a compose file which can be used in production.

feat: add production ready compose file

---

.vscode/launch.json
golang/cmd/crane/crane.go
golang/internal/config/config.go
golang/internal/mapper/pipe.go
golang/internal/mapper/pipe_test.go
golang/pkg/builder/container/container_builder_test.go
golang/pkg/crane/crane.go
golang/pkg/crane/k8s/clients.go
golang/pkg/crane/k8s/delete_facade.go
golang/pkg/crane/k8s/deploy_facade.go
golang/pkg/crane/k8s/secret.go
golang/pkg/dagent/utils/docker.go
golang/pkg/dagent/utils/docker_test.go
golang/pkg/helper/docker/container_test.go
golang/pkg/helper/docker/network_test.go

New:
- crane delete functions called
Fixes:
- log some swallowed errors
- moved some code into shared codebase

feat(crane): crane init & delete functions small fixes

---

web/crux/assets/install-script/install-docker.sh.hbr

fix(crux): joining script for nodes when using podman

---

golang/pkg/crane/crane.go
golang/pkg/crane/crux/deploy.go
golang/pkg/crane/k8s/deployment.go

Container/Deployment commands added to crane.
Added: start, stop, restart, all of them bumps the craneupdate annotation to `Now()`.

feat(crane): add deployment commands (start, stop, restart)

---

golang/api/v1/deploy.go
golang/pkg/dagent/utils/docker.go
golang/pkg/dagent/utils/import_container.go
golang/pkg/dagent/utils/import_container_test.go
golang/pkg/dagent/utils/init_container.go
golang/pkg/dagent/utils/volume.go

Done: 
- add arbitrary init container implementation
- containers stay in exited status after running to preserve logs

feat(dagent): add init container implementation

---

.chglog/config.yml
.github/workflows/full.yml
golang/pkg/cli/container_defaults.go

Expanded the conditional dependencies at the push steps, fixed a missing env in e2e step.

ci: fix pipeline image push

---

golang/internal/runtime/container/container.go
golang/internal/runtime/container/container_test.go
golang/pkg/cli/config_file.go
golang/pkg/cli/runner.go
golang/pkg/dagent/config/config.go
golang/pkg/dagent/utils/docker.go
golang/pkg/dagent/utils/preflight.go
golang/pkg/helper/image/image_integration_test.go
golang/pkg/helper/image/image_test.go

This PR adds container runtime version checking

feat: add container runtime version checking

---

golang/pkg/cli/cli.go
golang/pkg/cli/config_file.go

Added a flag to disable chatty texts eg. use-case is pipelines.

feat(cli): add silent mode, hiding welcome message

---

golang/pkg/cli/container_defaults.go

Geri find the missing piece, here is the one-line fix.

fix(cli): add missing protocol for CRUX_UI_URL

---

README.md

docs: change for to where in README

---

web/crux/src/app/shared/shared.dto.ts
web/crux/src/app/shared/shared.mapper.ts

Remove unnecessary optional from `AuditDto` and add default value to `createdBy` in mapper.

fix(crux): createdBy mapping

---

web/crux/src/app/deploy/deploy.http.controller.ts
web/crux/src/app/image/image.http.controller.ts
web/crux/src/app/version/version.http.controller.ts

PR contains the following fix: _fix swagger (and probably the c# generator) doesn't care about controller route params_ issue from JIRA.

fix(crux): controller route params

---

web/crux/src/app/audit/audit.dto.ts
web/crux/src/app/audit/audit.http.controller.ts
web/crux/src/app/dashboard/dashboard.http.controller.ts
web/crux/src/app/deploy/deploy.http.controller.ts
web/crux/src/app/image/image.http.controller.ts
web/crux/src/app/metrics/metrics.controller.ts
web/crux/src/app/node/node.http.controller.ts
web/crux/src/app/notification/notification.http.controller.ts
web/crux/src/app/product/product.dto.ts
web/crux/src/app/product/product.http.controller.ts
web/crux/src/app/registry/registry.http.controller.ts
web/crux/src/app/storage/storage.http.controller.ts
web/crux/src/app/team/team.http.controller.ts
web/crux/src/app/template/template.http.controller.ts
web/crux/src/app/token/token.http.controller.ts
web/crux/src/app/version/version.http.controller.ts

The PR contains a few Swagger & NestJS improvements around the HTTP endpoints.

fix(crux): OpenAPI improvements 

---

web/crux/src/app/audit/audit.dto.ts
web/crux/src/app/deploy/deploy.dto.ts
web/crux/src/app/image/image.dto.ts
web/crux/src/app/node/node.dto.ts
web/crux/src/app/shared/shared.dto.ts

Done:
- @polaroi8d found missing optionals, fixed.

fix(crux): add missing optionals to DTOs

---

.github/labeler.yml
.github/workflows/full.yml
.github/workflows/image-builder.yml
.github/workflows/image-tester.yml
.github/workflows/labeler.yml
golang/build/cli/Dockerfile
web/crux-ui/tailwind.config.js

This PR adds automatic labeling functions to PRs. It will scour the changeset and tries to make an educated guess about what label should be appropriate.

feat(ci): add pr labeler

---

web/crux/src/app/audit/audit.http.controller.ts
web/crux/src/app/dashboard/dashboard.http.controller.ts
web/crux/src/app/deploy/deploy.http.controller.ts
web/crux/src/app/health/health.http.controller.ts
web/crux/src/app/image/image.http.controller.ts
web/crux/src/app/node/node.global-container.http.controller.ts
web/crux/src/app/node/node.http.controller.ts
web/crux/src/app/node/node.prefix-container.http.controller.ts
web/crux/src/app/notification/notification.http.controller.ts
web/crux/src/app/product/product.dto.ts
web/crux/src/app/product/product.http.controller.ts
web/crux/src/app/registry/registry.http.controller.ts
web/crux/src/app/storage/storage.http.controller.ts
web/crux/src/app/team/team.http.controller.ts
web/crux/src/app/team/user.http.controller.ts
web/crux/src/app/template/template.http.controller.ts
web/crux/src/app/token/token.http.controller.ts
web/crux/src/app/version/version.http.controller.ts

OpenAPI documentation improved with response descriptions.

feat(crux): OpenAPI description improvements

---

.github/FUNDING.yml

PR contains our Open Collective profile link.

feat(docs): add open collective link to the repository

---

.github/workflows/full.yml
.github/workflows/title_validation.sh

PR introducing PR title validation tailored to our customs. Since we made some typos and our conventions changed a bit this one only covers roughly 90% of pr titles/ change messages.

feat(ci): validate title of the PR

---

.github/labeler.yml
.github/title_labeler.yml
.github/workflows/labeler.yml

This PR adds label based on the title.

feat(ci): add PR labeling based on title

---

.github/labeler.yml
images/alpine-proto/Dockerfile
images/playwright/Dockerfile
web/.env.example
web/kratos/Dockerfile

This PR fixes the weird behaviour of the automatic labeler.

fix(ci): PR labeling based on changes

---

.github/title_labeler.yml
.github/workflows/title_validation.sh

This PR fixes missing regexes that failed to label some PRs properly

fix(ci): labeling by title

---

README.md

fix: reorder some of the sections in the README.md

---

.env.example
docker-compose.http-only.yaml
docker-compose.yaml

This PR fixes database healthchecks in global docker compose files. Also fixes some formatting, and minor things.

fix: production compose database healthcheck user

---

.github/workflows/full.yml

Force rebuild everything when we are on: main or develop branches, current commit is tagged.

fix(ci): rebuild everything on release

---

.github/workflows/check_version.sh

check_version.sh was not sh compilant, this PR will make the if statement sh compilant

fix(ci): check_version.sh sh compilance

---

golang/cmd/dyo/main.go
golang/pkg/cli/cli.go
golang/pkg/cli/config_file.go
golang/pkg/cli/container_defaults.go
golang/pkg/cli/display.go
golang/pkg/cli/runner.go

WIP, stuff has rough edges, but feels a lot cleaner. Also untested.
PR adds documentation to exported/public functions, cleans up some functions, removes unnecessary arguments, fix up a few minor things.

refactor(cli): add documentation, clean up, fix minor bugs

---

.github/workflows/full.yml
.github/workflows/pipeline_set_output_tag.sh

This PR fixes the settag step where the tag always evaluated as "latest".

fix(ci): fix stable push on main branch

---

.github/workflows/full.yml
.github/workflows/image-builder.yml
.github/workflows/image-tester.yml
.yamlfmt

As requested: https://github.com/dyrector-io/dyrectorio/pull/580#issuecomment-1536402997
This PR adds YAML validation/linting to the pipeline.
Also fixing broken signing, since cosign had introduced some changes how you should use their software.
PR #580 and #586 are **required** for this.

feat(ci): add yaml validation to the pipeline

---

README.md

Nothing extra, just add back the how it work, high level diagram about the communication between services.

docs: add back the how it works image

---

web/crux/src/websockets/namespace.spec.ts
web/crux/src/websockets/namespace.ts

Add unit test for WsNamespace's onUnsubscribe() method.

test(crux): WsNamespace onUnsubscribe unit tests

---

.github/workflows/full.yml
web/crux-ui/e2e/utils/mail-slurper.ts
web/crux-ui/jest.config.ts
web/crux-ui/locales/en/nodes.json
web/crux-ui/package-lock.json
web/crux-ui/package.json
web/crux-ui/src/components/nodes/node-containers-list.tsx
web/crux-ui/src/components/products/versions/version-deployments-section.tsx
web/crux-ui/src/models/container.ts
web/crux-ui/src/models/container.unit.test.ts
web/crux-ui/src/pages/deployments.tsx
web/crux-ui/tsconfig.json

PR contains: 
- Fix the external and internal missleadings
- Add Jest to crux-ui scope
- Add unit test jobs for the pipeline
- Remove unused jobs from the pipeline regarding to crux build
- Add extra dependencies for tests (lint)

feat(web): add jest to ui and fix the container (internal) missleadings

---

web/crux-ui/Dockerfile
web/crux/Dockerfile

Fix docker builds of node based packages.

fix(web): node builds

---

Makefile

Can be used for hotfixes from now on.

build: remove branch from release target

---

golang/internal/runtime/container/container.go
golang/pkg/cli/runner.go

CLI version was missing from the output, minor improvement.

feat(cli): add CLI version in addition to runtime versions

---

web/crux-ui/e2e/nodes.spec.ts
web/crux-ui/src/components/nodes/dyo-node-setup.tsx
web/crux-ui/src/models/node.ts
web/crux-ui/src/validations/node.ts

The API refactor might have caused a little thrift, I've renamed the UI to match the backend.

fix(web): rename field to make Traefik work again

---

.github/workflows/staging-deploy.yaml

https://github.com/dyrector-io/dyrectorio/pull/649
We can proceed with skipping AD altogether, not as nice and clean, until it is sorted out it could help.

build: add staging deploy workflow

---

.github/workflows/full.yml

Multiarch images seem to be overwritten by non-multiarch images, this might be the culprit.

build: remove signing from multiarch images

---

golang/crane-test.yaml
golang/internal/helper/docker/container_test.go
golang/internal/helper/image/image_integration_test.go
golang/internal/helper/image/image_test.go
golang/pkg/builder/container/container_builder_test.go
golang/pkg/builder/container/exec_builder_test.go
golang/pkg/dagent/external/images/nginx.Dockerfile
web/crux-ui/e2e/deployment-copiability.spec.ts
web/crux-ui/e2e/deployment.spec.ts
web/crux-ui/e2e/nodes.spec.ts
web/crux-ui/e2e/registry.spec.ts
web/crux-ui/e2e/utils/common.ts
web/crux-ui/e2e/utils/global-setup.ts
web/crux-ui/e2e/utils/projects.ts
web/crux/package-lock.json

Dockerhub images must go because of accidental rate limit.

test(web): change test images to ghcr from dockerhub

---

.github/workflows/product_builder.yaml

fix(ci): minor versioning with crux push

---

.github/workflows/product_builder.yaml
web/crux-ui/.gitignore
web/crux-ui/Dockerfile
web/crux/.gitignore
web/crux/Dockerfile

This PR will add caching to crux, crux-ui and golang(cli, dagent, crane) processes including linting, testing and building.

feat(ci): add cache

---

.github/workflows/builder_image_signer.yaml
.github/workflows/product_builder.yaml
.github/workflows/tester_image_builder.yaml
images/signer/Dockerfile

Pipeline was unfortunately broken.

fix: add crane to signer image and add additional cache restore

---

web/crux-ui/locales/en/deployments.json
web/crux-ui/locales/en/nodes.json
web/crux-ui/locales/en/tokens.json
web/crux-ui/src/components/nodes/edit-node-card.tsx
web/crux-ui/src/components/projects/versions/deployments/create-deployment-token-card.tsx
web/crux-ui/src/components/projects/versions/images/edit-image-card.tsx
web/crux-ui/src/components/projects/versions/images/use-image-editor-state.ts
web/crux-ui/src/components/projects/versions/use-version-state.ts
web/crux-ui/src/components/projects/versions/version-deployments-section.tsx
web/crux-ui/src/components/projects/versions/version-images-section.tsx
web/crux-ui/src/components/projects/versions/version-sections-heading.tsx
web/crux-ui/src/components/projects/versions/version-sections.tsx
web/crux-ui/src/components/projects/versions/version-view-list.tsx
web/crux-ui/src/components/projects/versions/version-view-tile.tsx
web/crux-ui/src/components/projects/versions/versionless-project-sections.tsx
web/crux-ui/src/elements/dyo-modal.tsx
web/crux-ui/src/pages/deployments.tsx
web/crux-ui/src/pages/deployments/[deploymentId].tsx
web/crux-ui/src/pages/projects/[projectId]/versions/[versionId].tsx

- Add delete button to the deployments page.
- Fix labels for version deployments actions

feat(crux-ui): add delete button to deployments list

---

go.mod
golang/internal/helper/docker/container.go
golang/internal/helper/docker/container_test.go
golang/internal/helper/image/image.go
golang/internal/helper/image/image_integration_test.go
golang/internal/helper/image/image_test.go
golang/internal/runtime/container/container.go
golang/internal/runtime/container/container_test.go
golang/pkg/builder/container/container_builder.go
golang/pkg/dagent/update/update.go
golang/pkg/dagent/update/update_integration_test.go
golang/pkg/dagent/update/update_test.go
golang/pkg/dagent/utils/container.go
golang/pkg/dagent/utils/docker.go
golang/pkg/dagent/utils/dockerhelper.go

More user friendly errors for updates. New mocks, tests for a few image functions.
Traefik pull fix.

fix(dagent): rewrite image errors for update, add tests

---

CONTRIBUTING.md

doc: add branching strategy to CONTRIBUTING.md

---

web/crux-ui/locales/en/common.json
web/crux-ui/package-lock.json
web/crux-ui/src/components/projects/versions/deployments/use-deployment-state.tsx
web/crux-ui/src/components/projects/versions/use-version-state.ts
web/crux-ui/src/elements/web-socket-save-indicator.tsx
web/crux-ui/src/hooks/use-interval.ts
web/crux-ui/src/hooks/use-timer.ts
web/crux-ui/src/models/common.ts
web/crux-ui/src/pages/projects/[projectId].tsx
web/crux-ui/src/pages/projects/[projectId]/versions/[versionId]/images/[imageId].tsx
web/crux-ui/src/websockets/websocket-client.ts
web/crux-ui/tailwind.config.js
web/crux/package-lock.json

- Update crux and crux-ui dependencies
- Hide ws save indicator automatically
- Hide ws save indicator on versioned project details page

feat(web): websocket save indicator refinement

---

web/crux/prisma/migrations/20230705131535_deployment_token_audit/migration.sql

Fixes an issue with the deployment token audit log migration.

fix(crux): failing deployment token migration

---

.golangci.yml
golang/internal/mapper/grpc.go

Panic could be triggered with empty domain.

fix(dagent): handle pointers correctly in route mapping

---

web/crux-ui/Dockerfile
web/crux/Dockerfile
web/kratos/Dockerfile

Add healthchecks for docker to display if a container is healthy or not.

feat: add HEALTHCHECK directives to every platform image

---

CONTRIBUTING.md
GETTING_STARTED.md
README.md

Pruned the README.md contents for readability & tidiness.

doc: add GETTING_STARTED.md, small section rewrites

---

.gitignore
Makefile
offline/import.sh
offline/importar.sh

Refactored the previous version, added a minimal and a full make target.

chore: new export dyrectorio offline bundle

---

web/crux-ui/locales/en/container.json
web/crux-ui/src/components/projects/versions/images/config/common-config-section.tsx
web/crux-ui/src/components/projects/versions/images/config/crane-config-section.tsx
web/crux-ui/src/components/projects/versions/images/config/dagent-config-section.tsx
web/crux-ui/src/components/shared/secret-key-value-input.tsx
web/crux-ui/src/pages/[teamSlug]/deployments/[deploymentId]/instances/[instanceId].tsx
web/crux-ui/src/pages/[teamSlug]/projects/[projectId]/versions/[versionId]/images/[imageId].tsx
web/crux-ui/src/validations/container.ts
web/crux/src/domain/validation.ts

Added error messages to Docker and missing errors to Kubernetes in image config.

fix(crux-ui): image config error text

---

web/crux/package-lock.json
web/crux/package.json

This solves the vm2 critical vulnerability that was given by dependabot.

chore(crux): fix vm2 critical vuln using npm audit fix

---

README.md

Updating the readme, attached the new view, left is the new one.

chore: readme styling

---

.github/workflows/deploy_external.yaml
CONTRIBUTING.md
GETTING_STARTED.md
MAINTAINERS.md
SECURITY.md

- Remove hardcoded URL from the external pipeline
- Enhance the external pipeline to exit with status 1 in case of curl failure
- Update maintainers' documentation
- Format `.md` files

cicd: remove hardcoded values and small changes

---

DEVELOPMENT.md

Added label description to development.md

doc: update development.md

---

web/crux-ui/locales/en/common.json
web/crux-ui/locales/en/nodes.json
web/crux-ui/src/components/nodes/edit-node-section.tsx
web/crux-ui/src/components/nodes/node-connection-card.tsx
web/crux-ui/src/components/projects/versions/deployments/use-deployment-state.tsx
web/crux-ui/src/models/node.ts
web/crux-ui/src/pages/[teamSlug]/nodes.tsx
web/crux/src/app/agent/agent.service.ts
web/crux/src/app/agent/connection-strategies/agent.connection.legacy.strategy.ts
web/crux/src/app/deploy/interceptors/deploy.start.interceptor.ts
web/crux/src/app/node/node.dto.ts
web/crux/src/app/node/node.http.controller.ts
web/crux/src/app/node/node.mapper.ts
web/crux/src/app/node/node.message.ts
web/crux/src/domain/agent.spec.ts
web/crux/src/domain/agent.ts

- Agent update button now gets disabled, when there is no update available.
- Add `updating` as an agent status

feat(web): agent update button availability

---

DEVELOPMENT.md
MAINTAINERS.md
SECURITY.md

Development.md
- change the path to the `AGENT_PROTO_COMPATIBILITY_MINIMUM_VERSION` and added a link to the const.ts file.
- add white space to improve readability
Maintainers.md
- update grammar to improve readability
Security.md
- add links to dyrector.io
- add mailto links to email address

doc: update development.md, maintainers.md and security.md

---

CONTRIBUTING.md
README.md

doc: improved-readme-and-contributing-file-issue-827
Issue - https://github.com/dyrector-io/dyrectorio/issues/827
Fixed 5 links in contributing file and 2 links in readme file.
Kindly review it once.
Thank you.

doc: improve-readme-and-contributing-files

---

web/crux-ui/src/utils.ts
web/crux/src/services/kratos.service.ts

Fixes a bug with kratos identity listing.

fix: identity listing

---

web/crux-ui/src/websockets/websocket-client.ts

Now navigating away from a websocket-using page there will be no confusing error toast displayed.

fix: unnecessary websocket error toasts

---

web/crux-ui/src/components/layout.tsx
web/crux-ui/src/components/main/sidebar.tsx

Fixes sidebar scaling and vertical grow on non 16:9 displays.

fix(crux-ui): sidebar vertical grow

---

.github/workflows/product_builder.yaml
web/crux-ui/locales/en/registries.json
web/crux-ui/package-lock.json
web/crux-ui/src/components/registries/registry-fields/hub-registry-fields.tsx
web/crux-ui/src/error-responses.ts
web/crux-ui/src/models/registry.ts
web/crux-ui/src/validations/registry.ts
web/crux/src/app/registry/guards/registry.auth.validation.guard.ts
web/crux/src/app/registry/registry-client.provider.ts
web/crux/src/app/registry/registry-clients/cached-hub-api-client.ts
web/crux/src/app/registry/registry-clients/hub-api-client.ts
web/crux/src/app/registry/registry-clients/private-hub-api-client.ts
web/crux/src/app/registry/registry.dto.ts
web/crux/src/app/registry/registry.mapper.ts
web/crux/src/exception/crux-exception.ts

Add private docker hub registry support.

feat(web): add private docker hub registry support

---

web/crux-ui/src/components/config-bundles/config-bundle-card.tsx
web/crux-ui/src/components/nodes/dyo-node-card.tsx
web/crux-ui/src/components/notifications/notification-card.tsx
web/crux-ui/src/components/projects/project-card.tsx
web/crux-ui/src/components/projects/project-versions-section.tsx
web/crux-ui/src/components/projects/project-view-tile.tsx
web/crux-ui/src/components/projects/versions/version-card.tsx
web/crux-ui/src/components/registries/registry-card.tsx
web/crux-ui/src/components/storages/storage-card.tsx
web/crux-ui/src/pages/[teamSlug]/config-bundles.tsx
web/crux-ui/src/pages/[teamSlug]/nodes.tsx
web/crux-ui/src/pages/[teamSlug]/nodes/[nodeId].tsx
web/crux-ui/src/pages/[teamSlug]/notifications.tsx
web/crux-ui/src/pages/[teamSlug]/notifications/[notificationId].tsx
web/crux-ui/src/pages/[teamSlug]/registries.tsx
web/crux-ui/src/pages/[teamSlug]/registries/[registryId].tsx
web/crux-ui/src/pages/[teamSlug]/storages.tsx
web/crux-ui/src/pages/[teamSlug]/storages/[storageId].tsx

Replace `titleHref` properties in `Card` components with `disableTitleHref`

refactor(crux-ui): title hrefs

---

golang/internal/runtime/container/container_test.go
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/0c6db3b8317ee4fe
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/0c6db3b8317ee4ff
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/1d45cabffa6e7b5e
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/7e4eb17cc2f63430
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/a16632e73a615d5a
golang/internal/runtime/container/testdata/fuzz/FuzzVersionCheckDocker/b51a043bfdbca469

Fuzz testing to all the number inputs for both Podman and Docker.

test(agent): add fuzz testing for docker version checks

---

web/crux/src/app/pipeline/pipeline.http.controller.ts
web/crux/src/app/pipeline/pipeline.service.ts
web/crux/src/domain/pipeline.ts
web/crux/src/services/azure-devops.service.ts

- Fixes a bug, where the correct teamSlug was missing from the pipeline hook url.

fix(crux): missing teamslug from pipeline hooks

---

README.md

Small adjustments in the `README.md`

doc: braking typo fix and smaller adjustments

---

web/crux-ui/e2e/with-login/notification.spec.ts
web/crux-ui/src/validations/notification.spec.ts
web/crux-ui/src/validations/notification.ts

Fix self-hosted rocket chat webhook validation.
Add unit-tests for webhook validations.

fix(crux-ui): notification webhook validations

---

golang/Makefile
web/crux-ui/e2e/utils/common.ts
web/crux-ui/package-lock.json
web/crux-ui/package.json
web/crux-ui/src/models/auth.ts
web/crux-ui/src/pages/api/auth/create-account.ts
web/crux-ui/src/pages/api/auth/login.ts
web/crux-ui/src/pages/api/auth/recovery.ts
web/crux-ui/src/pages/api/auth/register.ts
web/crux-ui/src/pages/api/auth/settings/change-password.ts
web/crux-ui/src/pages/api/auth/settings/edit-profile.ts
web/crux-ui/src/pages/api/auth/settings/oidc.ts
web/crux/package-lock.json
web/crux/package.json
web/crux/src/services/kratos.service.ts
web/kratos/Dockerfile

feat(web): update kratos to 1.1.0

---

docker-compose.http-only.yaml
docker-compose.yaml

As the title says. Thanks 'Rawennum' for reporting the bug in our Discord server.

fix(crux): add ENCRYPTION_SECRET_KEY to compose files

---

web/crux/src/app/registry/registry-clients/github-api-client.ts
web/crux/src/app/registry/registry-clients/gitlab-api-client.ts
web/crux/src/app/registry/registry-clients/google-api-client.ts
web/crux/src/app/registry/registry-clients/hub-api-client.ts
web/crux/src/app/registry/registry-clients/private-hub-api-client.ts
web/crux/src/app/registry/registry-clients/v2-api-client.ts
web/crux/src/app/registry/registry-clients/v2-labels.ts

Fix label fetching for github registry images.

fix(crux): github label fetching

---

web/crux-ui/locales/en/common.json
web/crux-ui/quality-assurance.ts
web/crux-ui/src/components/nodes/node-containers-list.tsx
web/crux-ui/src/elements/dyo-modal.tsx
web/crux-ui/src/hooks/use-info-modal.ts

Truncate ports in node container list.
Add an option to check all ports in a dialog.

feat(crux-ui): truncate ports in container list

---

web/crux-ui/src/elements/dyo-table.tsx

Remove unsorted option from sorted lists.

fix(crux-ui): simplify list sorting

---

web/crux/src/app/token/jwt-auth.guard.ts
web/crux/src/app/token/token.service.ts
web/crux/src/shared/const.ts
web/crux/src/websockets/dyo.ws.adapter.ts

- Fix a segfault while receiving a websocket message without subscribing first to the namespace
- Fix user token based websocket authentication

fix: websocket authentication with user tokens

---

web/crux-ui/e2e/utils/common.ts
web/crux-ui/e2e/utils/node-helper.ts
web/crux-ui/e2e/with-login/nodes-deploy.spec.ts
web/crux-ui/e2e/with-login/nodes.spec.ts

Add an e2e for watch container status hanging.

test: watch container status hanging

---

.golangci.yml
golang/internal/mapper/grpc.go
golang/internal/mapper/grpc_test.go
golang/pkg/dagent/utils/docker.go

Magic numbers were uncovered and are addressed here.

chore(agent): remove magic numbers, adjust related rules

---

web/crux/src/app/node/node.container.http.controller.ts

feat(crux): get container list api

---

.github/workflows/pipeline_set_output_tag.sh
.github/workflows/product_builder.yaml

The pipeline runs twice for releases, that had undesirable side-effects.

cicd: tag version only from release

---

web/crux-ui/locales/en/versions.json
web/crux-ui/src/components/projects/edit-project-card.tsx
web/crux-ui/src/components/projects/versions/edit-version-card.tsx
web/crux-ui/src/models/version.ts
web/crux-ui/src/pages/[teamSlug]/projects/[projectId]/versions/[versionId].tsx
web/crux/prisma/migrations/20240522094419_version_copy_deployments/migration.sql
web/crux/prisma/schema.prisma
web/crux/src/app/version/version.dto.ts
web/crux/src/app/version/version.mapper.ts
web/crux/src/app/version/version.service.ts
web/crux/src/domain/version-increase.ts

- Add a toggle for automatic deployment copy on version increment
- Copy deployments while increasing a version depending on the said toggle.

feat(web): add option to disable deployment copy on version increase

---

web/crux-ui/src/components/projects/versions/version-reorder-images-section.tsx
web/crux-ui/src/components/shared/drag-and-drop-list.tsx

- Fixes a bug with image ordering after modifying an image.

fix(crux-ui): image ordering

---

web/crux-ui/package-lock.json
web/crux-ui/package.json
web/crux/package-lock.json
web/crux/package.json
web/kratos/Dockerfile
web/kratos/kratos.template.yaml

feat: update kratos to 1.12.0

---

web/crux-ui/Dockerfile
web/crux/Dockerfile

The executable to manage, load custom certs was missing. The PR addresses the issue for crux, crux-ui containers.

feat(web): add executable to manage custom certs

---

web/crux-ui/src/components/registries/edit-registry-card.tsx
web/crux-ui/src/components/registries/registry-fields/unchecked-registry-field.tsx
web/crux-ui/src/models/registry.ts
web/crux-ui/src/validations/registry.ts
web/crux/src/app/registry/registry.dto.ts
web/crux/src/app/registry/registry.mapper.ts

Add optional credentials for unchecked registries.

feat(web): add private unchecked registry

---

web/crux-ui/package-lock.json

`npm audit fix` > https://github.com/dyrector-io/dyrectorio/actions/runs/11888287384/job/33134753555

fix(crux-ui): For Next.js, Node.js version >= v18.17.0 is required.

---

.github/workflows/product_builder.yaml

GitHub refuses to run pipelines, thus we must migrate.

cicd: migrate to artifacts@v4

---

golang/cmd/crane/crane.go
golang/cmd/dagent/dagent.go
golang/internal/grpc/grpc.go
golang/pkg/crane/crane.go
golang/pkg/dagent/caps/parser.go
golang/pkg/dagent/dagent.go

Nice to have, we don't need no panics.

refactor(agent): remove unnecessary panic calls

---

.vscode/settings.json
go.mod
golang/internal/backoff/backoff.go
golang/internal/backoff/backoff_test.go
golang/internal/grpc/grpc.go

Added some backoff to our agent grpc reconnect.

fix(agent): add backoff to reduce reconnect load

---

web/crux-ui/e2e/with-login/container-config/common-editor.spec.ts
web/crux-ui/e2e/with-login/container-config/common-json.spec.ts
web/crux-ui/e2e/with-login/container-config/docker-editor.spec.ts
web/crux-ui/e2e/with-login/container-config/docker-json.spec.ts
web/crux-ui/e2e/with-login/container-config/kubernetes-editor.spec.ts
web/crux-ui/e2e/with-login/container-config/kubernetes-json.spec.ts
web/crux-ui/e2e/with-login/deployment/deployment-mutability-versioned.spec.ts
web/crux-ui/e2e/with-login/deployment/deployment-mutability-versionless.spec.ts
web/crux-ui/locales/en/container.json
web/crux-ui/package-lock.json
web/crux-ui/src/components/container-configs/common-config-section.tsx
web/crux-ui/src/components/container-configs/config-section-label.tsx
web/crux-ui/src/components/container-configs/container-config-filters.tsx
web/crux-ui/src/components/container-configs/crane-config-section.tsx
web/crux-ui/src/components/container-configs/dagent-config-section.tsx
web/crux-ui/src/components/container-configs/extendable-item-list.tsx
web/crux-ui/src/components/projects/versions/images/edit-image-tags.tsx
web/crux-ui/src/components/shared/key-only-input.tsx
web/crux-ui/src/elements/dyo-message.tsx
web/crux-ui/src/models/container.ts
web/crux-ui/src/validations/container.ts
web/crux/.env.example
web/crux/package-lock.json
web/crux/src/app/image/image.service.ts
web/crux/src/config/app.config.ts

- The container config layout now fills the whole screen instead of being arranged in 3 columns.
- Add an env variable to disable the registry image label fetching.
- Update npm packages.

feat: full width container config layout
